os: linux
sudo: required
language: "minimal"
services:
  - dockers

before_script:
  - docker build . --tag arcade
  - chmod 755 scripts/*.sh
  - echo $(pwd)
  - ls -la
  - ls -la Content

jobs:
  include:
    - name: "tests"
      script:
        - docker run --rm -t -v $(pwd):/arcade arcade scripts/tests.sh
    - name: "coverage"
      script:
        - docker run --rm -t -v $(pwd):/arcade arcade scripts/coverage.sh
    - name: "checks"
      script:
        - docker run --rm -t -v $(pwd):/arcade arcade scripts/checks.sh